// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rentit.main;

import com.rentit.main.Plant;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Plant_Roo_Configurable {
    
    declare @type: Plant: @Configurable;
    
}
